### ISSUE TITLE
gvoice app doesn't  login

### ISSUE THREAD

**Issue by mr-dallas** [pettazz/pygooglevoice#18]
for me everything the gvoice CLI seems to be broke, and cannot login.

Traceback (most recent call last):
  File "/usr/bin/gvoice", line 80, in <module>
    login()
  File "/usr/bin/gvoice", line 50, in login
    voice.login(options.email,options.passwd)
  File "/usr/local/lib/python2.7/dist-packages/googlevoice/voice.py", line 73, in login
    service = re.search(r"name=\"service\" type=\"hidden\" value=\"(.+)\"", content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

anyone else having this problem?

**Comment by twbarber** [comment]
Same issues here. I'll try and take a look at it tonight.

**Comment by mr-dallas** [comment]
> Same issues here. I'll try and take a look at it tonight.
> 

Thanks, I really depend on that program a lot,
and appreciate any effort you make!



Regards, Dallas E. Legan II / legan@acm.org / aw585@lafn.org
http://isthereanotherquestion.blogspot.com
************************************************************************
"Tekeli-li! Tekeli-li!"
        - "At the Mountains of Madness", H.P.
Lovecraft

---------------------------------------------
This message was sent using Endymion MailMan.
http://www.endymion.com/products/mailman/

**Comment by twbarber** [comment]
Got a chance to take a look, it looks like you may have an outdated version. That line should be:
```galx = re.search(r"type=\"hidden\"\s+name=\"GALX\"\s+value=\"(.+)\"", content).group(1)```
Can you update the version and try again?

**Comment by mr-dallas** [comment]
> Got a chance to take a look, it looks like you may have an outdated version. That line
should be:
> ```galx = re.search(r"type=\"hidden\"\s+name=\"GALX\"\s+value=\"(.+)\"",
content).group(1)```
> Can you update the version and try again?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/pettazz/pygooglevoice/issues/18#issuecomment-173074073

I'll try to soon.
I'm busy right now, but the gvoice sample app is *very* important to
me.

Thanks for your efforts!

Regards, Dallas E. Legan II / legan@acm.org / aw585@lafn.org
http://isthereanotherquestion.blogspot.com
************************************************************************
"Tekeli-li! Tekeli-li!"
        - "At the Mountains of Madness", H.P.
Lovecraft

---------------------------------------------
This message was sent using Endymion MailMan.
http://www.endymion.com/products/mailman/

**Comment by mr-dallas** [comment]
>
>
>
>
> Got a chance to take a look, it looks like you may have an outdated version. That line should be:
> ```galx = re.search(r"type=\"hidden\"\s+name=\"GALX\"\s+value=\"(.+)\"", content).group(1)```
> Can you update the version and try again?
>

finally found some time to upgrade python and re-install,
seems to be working fine.

Thanks, and appreciate your patience!

Regards, Dallas E. Legan II / legan@acm.org / dallas.legan@gmail.com
http://isthereanotherquestion.blogspot.com
************************************************************************
"Tekeli-li! Tekeli-li!"
        - "At the Mountains of Madness", H.P. Lovecraft

**Comment by aaronshim** [comment]
I'm getting the error when I try to log in. I've even abled "less secure apps" to log in through https://support.google.com/accounts/answer/6010255. I don't have two-factor turned on.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "googlevoice/voice.py", line 95, in login
    raise LoginError
googlevoice.util.LoginError
```

Any ideas on why this might be happening for some accounts?

**Comment by illgitthat** [comment]
@aaronshim try using a web browser (lynx for example) to login to Google Voice on the server you are running the script. It could be Google not allowing the login from the server that's in a different location than normal account logins.

Something to try!

**Comment by aaronshim** [comment]
That was it! Unfortunately, even after whitelisting my SSH box on my Google
account, the fraud detection algorithm still hasn't learned it yet, so I
resorted to running my script on my local machine with a recognized IP.

**Comment by chris001** [comment]
See #27 issue solved when you log into your google voice account then browse to the following page
https://accounts.google.com/DisplayUnlockCaptcha
>    **Allow access to your Google account**
>    As a security precaution, Google may require you to complete this additional step when signing into a new device or application.
>
>    To allow access, click the Continue button below.

**Comment by iannesbitt** [comment]
@twbarber I have the most recent version from github and am still getting the AttributeError referenced above:

```
File "/var/www/site/venv/lib/python2.7/site-packages/googlevoice/voice.py", line 75, in login
  galx = re.search(r"type=\"hidden\"\s+name=\"GALX\"\s+value=\"(.+)\"", content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

You can see I'm using a virtualenv, but I see no reason why that should matter here.

**Comment by gkuenning** [comment]
I submitted a pull request to fix this a few days ago.  Google has stopped providing the galx field.  So the cure is (a) delete the line you quoted (line 75), and (b) two lines later, in the do_page call, remove 'GALX': galx.
