### ISSUE TITLE
Login error even after changing login vars

### ISSUE THREAD

**Issue by Ajay-Ramachandran** [pettazz/pygooglevoice#22]
Traceback (most recent call last):
  File "/home/ajay/Desktop/pygooglevoice-master/examples/call.py", line 5, in <module>
    voice.login()
  File "/usr/local/lib/python2.7/dist-packages/pygooglevoice-0.5.1-py2.7.egg/googlevoice/voice.py", line 73, in login
    galx = re.search(r"name=\"GALX\" type=\"hidden\"\n *value=\"(.+)\"", content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ljluestc** [comment]
```
#!/usr/bin/env python
from googlevoice import Voice
import sys

# Initialize the Voice object
voice = Voice()

# Log in to Google Voice
try:
    voice.login()
except Exception as e:
    print(f"Failed to log in: {e}")
    sys.exit(1)

# Perform actions (e.g., make a call)
try:
    voice.call("1234567890", "0987654321")  # Replace with actual numbers
except Exception as e:
    print(f"Failed to make a call: {e}")
```
