### ISSUE TITLE
Login fails.  Anyone able to login?

### ISSUE THREAD

**Issue by chris001** [pettazz/pygooglevoice#27]
Using the master version from this repo.
It gives the login failure error.

```
~# gvoice send_sms +18005551212 "Test Message... "
Login failed. Retry?[Y/n]
```

When you run `sms.py` to get a stack trace it says:

```
~/pygooglevoice/examples # python sms.py
Traceback (most recent call last):
  File "sms.py", line 5, in <module>
    voice.login()
  File "/usr/lib/python2.7/site-packages/googlevoice/voice.py", line 96, in login
    raise LoginError
googlevoice.util.LoginError
```

The code raising the exception is in `voice.py` line 96

```
        try:
            assert self.special
        except (AssertionError, AttributeError):
            raise LoginError
```

From #21 #22 and #24 it makes no difference when you modify the `LOGIN` url in `settings.py` to remove all get parameters except `service=grandcentral` :

```
#LOGIN = 'https://accounts.google.com/ServiceLogin?service=grandcentral&passive=1209600&continue=https://www.google.com/voice&followup=https://www.google.com/voice&ltmpl=open'
LOGIN = 'https://accounts.google.com/ServiceLoginAuth?service=grandcentral'
```

Anyone else getting this `Login Failed` error ?

Could the login be failing because this code is using both `GET` and `POST` parameters, while the login web page itself uses only `POST` parameters ?

**Comment by tom-slick** [comment]
Code works as is with no changes.
Did you get everything right in your .gvoice file? 
```
[auth]
# Google Account email address (one associated w/ your Voice account)
email=name@gmail.com

# Raw password used or login
password=password

[gvoice]
# Number to place calls from (eg, your google voice number)
forwardingNumber=+12223334444

# Default phoneType for your forwardingNumber as defined below
#  1 - Home
#  2 - Mobile
#  3 - Work
#  7 - Gizmo
phoneType=2


```

**Comment by chris001** [comment]
@tom-slick 
Thanks for replying.
Yes the `.gvoice` file looks exactly like yours.
One discrepancy - this gmail account started its life as a simple google account with `name@yahoo.com` as the associated email, and later, added to the account a gmail address and a gmail inbox.
And the gmail address was set as the primary email on the account.
You can login as either email address.
Could this be why it's behaving differently??

**Comment by tom-slick** [comment]
I don't know.  I'm not in that situation so I could not even test that.

**Comment by chris001** [comment]
@tom-slick 
I tested it with a different google gmail account, this one has only a `name@gmail.com` address, no other previous outside email address associated to it, and it still fails :/
Had to visit this page to accept the new device and IP address, for security, since the pygooglevoice code is running on a different IP than usual PC.  https://security.google.com/settings/security/activity

**Comment by tom-slick** [comment]
I did a clean install of the software (no changes to the download) and then created the auth file and it logged in without errors on the first try.  It's not the code, it does work.

**Comment by chris001** [comment]
@tom-slick  Which operating system and python version are you running?  Just to check...  Here it's centos 7 and python 2.7

**Comment by tom-slick** [comment]
Debian and Raspbian. python 2.7

**Comment by chris001** [comment]
Thanks @tom-slick   :beers:
FYI for anyone else with this issue. The **master** code from the pettazz repo is working fine, in debian raspbian and centos 7 OS.
The problem is gvoice security.
You must do the "gvoice reset procedure", which allows the gvoice app to login from the new "Device," when you're running this code on a device which is different device from your usual pc/device.
GVoice reset procedure: 
https://accounts.google.com/DisplayUnlockCaptcha
>     Allow access to your Google account
>    As a security precaution, Google may require you to complete this additional step when signing into a new device or application.
>
>    To allow access, click the Continue button below.

**Comment by nalipaz** [comment]
None of this is working for me. Still can't login on arm architecture, debian 8. Trying with python2.7 right now.

**Comment by nalipaz** [comment]
BTW, I see the code in voice.py that should prompt for an smsKey when unset, that never happens. I also tried setting smsKey in my .gvoice file and that doesn't help. 2-factor authentication still seems broken. Visiting the above url does not prompt for a captcha to unlock and instead only provides me with a continue link. Also, I have tried this both with my real password as well as an app password.

**Comment by chris001** [comment]
@nalipaz 
The url https://accounts.google.com/DisplayUnlockCaptcha is supposed to only show a Continue button, all it does is allow the IP address you're browsing on, to have permission to login to the GVoice account.

**Comment by chris001** [comment]
Tested `gvoice send_sms 18005551212 Hello trying out the send_sms right now` and it still works on Centos 7 Python 2.7.5.  
`~/.gvoice` contains `email=` account email, `password=` the raw clear text password, and `phoneType=2` for Mobile.
`smsKey` is not necessary for you to provide, the app gets that key by itself while it talks to gvoice, as part of its login.
What's the error it gives you, can you copy and paste it.

**Comment by nalipaz** [comment]
Turns out it is all related to two-factor authentication not working, reported in another issue.

**Comment by dzimbeck** [comment]
Unlock Captcha doesn't work either

**Comment by chris001** [comment]
@dzimbeck  How about if you disable two-factor authentication on the google account settings.  Then will it let you login?

**Comment by dzimbeck** [comment]
There is no two factor authentication set.
I've tried with multiple Gmail. So has a friend of mine on other computers. This package used to work for us, now it doesnt.

Please test it and patch it.

**Comment by dzimbeck** [comment]
It broke recently out of nowhere. I submitted a new issue. Google probably changed something again.

**Comment by chris001** [comment]
Here the login worked on 8th and 9th Feb, and is broken today 10th Feb.

**Comment by chris001** [comment]
They released a nicer web interface, with slight changes.

**Comment by dzimbeck** [comment]
It wasn't working for us on the 9th either. We just get perpetual Auth errors regardless of email, I always get a notification at my gmail when it fails logging in. Even unlock captcha, nothing seems to work.

Did they change their login url again?

**Comment by chris001** [comment]
Further information:  The code actually logs in, but it thinks that the login failed.  Probably due to the change in the web interface text.  Looking into it..
Run the app, then see for yourself that you have logged in successfully, by visiting here, it will say the user agent of your app, "recently used devices - just now - new": 
https://myaccount.google.com/device-activity?pli=1

**Comment by dzimbeck** [comment]
Thank you for noticing this! This is exactly what I'm seeing. But the main question is, can a patch be applied so that the library can text and call again and not think it's login has failed? I've got it in a try/except catch. I could change my code but will it actually text if I ignore this error? It makes more sense to push a fix and eventually close this issue.

**Comment by chris001** [comment]
Yes it's best to fix the part where it's deciding whether the login was successful, so that a truly incorrect login is accurately reported back to the user.  Looking at it now.

**Comment by chris001** [comment]
Issue #36 is a duplicate of this one.
1. The reason why the login appears to have broken, is because the variable name for the login session has  changed, from `_rnr_se` to something else - haven't had time yet to get in the and find the new variable name.
2. Also, the page URL for the inbox has changed, from `https://www.google.com/voice/b/0/#inbox` to `https://voice.google.com/messages`.
3. Likewise, the new page url for voicemail is `https://voice.google.com/voicemail`.
4. There's a whole new upgraded web interface, this is why the code is having problems, they didn't keep the old variable names or page URLs.  It has to be looked at and analyzed and the new variable names and page URLs found and tested.  There's about 20 of them.  Volunteers?

**Comment by dov1** [comment]
The url is the same and it's still _rnr_se. The problem is in voice.py the regex is incorrect. So re.search is not finding the key. I hardcoded sp="my _rnr_se key" into voice.py and recompiled and it worked.
By the way, _rnr_se is a constant. I logged in from several devices and they all got the same _rnr_se key.

**Comment by dov1** [comment]
After testing, I found the regex is correct. The problem is that even though the url for settings.INBOX is correct, urlopen is getting the mobile version of the page and _rnr_se is not on the mobile version, only the desktop version. I've tried various user agent strings but was unsuccessful in getting the desktop version. I hope someone can add some input here.

**Comment by chris001** [comment]
I took a quick look and believe the login session token is being passed in the post parameters for the login.  It was a few days ago, I have to look at it again to get more details.

**Comment by dov1** [comment]
I fixed it by changing BASE = 'https://www.google.com/voice/b/0/redirection/voice' in settings.py

**Comment by dov1** [comment]
Well that has issues too. If you go to a different folder and try going back to inbox it errors. We only need to access /redirection/voice once. After that it gets confused.

**Comment by dov1** [comment]
The LOGIN_POST continue link seems to be the best place to put it.
&continue=https://www.google.com/voice/redirection/voice

**Comment by dov1** [comment]
The error going back to the inbox folder seems to be unrelated.

**Comment by chris001** [comment]
The login_post continue link fixes the login here.  Able to login, send an sms, quit, and it sends.
What's the exact series of commands you do to make it error/fail?

**Comment by dov1** [comment]
At the gvoice> prompt
sms
inbox

**Comment by dov1** [comment]
The only thing I needed it to work for was call. Which is why I didn't notice the other errors at first. After I posted it here, I figured I should test other features in case anyone uses them and found the errors.

**Comment by chris001** [comment]
Yes of course all the features should work like the used to work.
For you it crashes immediately after you do `sms` then `inbox`?
What is the error word for word? Can you copy/paste the error.

**Comment by dov1** [comment]
I'm not at that computer now. But in short after sms then inbox there was a break in the script, it displayed errors on a few lines, and exited to the shell.

**Comment by chris001** [comment]
Can you post all of your `settings.py` here, except for private information, username/password/exact phone number.  But include a blank phone number in the same format as the one you're using.

**Comment by dov1** [comment]
The only thing I changed in settings.py is the LOGIN_POST &continue link.
The format of the phone number both for forwarding and outgoing is +1xxxxxxxxxx

**Comment by dov1** [comment]
What I get after issuing commands sms and then inbox

Traceback (most recent call last):
  File "/usr/local/bin/gvoice", line 113, in <module>
    elif action in ('inbox','i'): pprint_folder('inbox')
  File "/usr/local/bin/gvoice", line 67, in pprint_folder
    pprint(folder.messages,indent=4)
  File "/usr/local/lib/python2.7/dist-packages/googlevoice/util.py", line 242, in messages
    return [Message(self, *i) for i in self['messages'].items()]
  File "/usr/local/lib/python2.7/dist-packages/googlevoice/util.py", line 181, in __init__
    assert is_sha1(id), 'Message id not a SHA1 hash'
AssertionError: Message id not a SHA1 hash

    Logging out of voice...

**Comment by chris001** [comment]
That's interesting, the same commands in the same order are working fine here.
What happens after you edit `settings.py` and set `Debug = True` and try `gvoice`, `sms`, `inbox` again.

**Comment by dzimbeck** [comment]
So is this package still broken?

**Comment by dov1** [comment]
The change I proposed fixes it. It hasn't been merged but it's simple
enough to make the change yourself.

**Comment by dov1** [comment]
Oops. I forgot to remove the quoted text before sending reply.

**Comment by chris001** [comment]
@dov1 I thought the package was still broken when you do the commands `sms` then `inbox` ??  Is that series of commands working now for you? What have you changed to get those commands to work for you?

**Comment by dov1** [comment]
It's an unrelated issue. I haven't gotten a chance to test it but it might
have to do with the number of unread messages in the folder.

**Comment by chris001** [comment]
You can make a small change to the code to see more information about why it's crashing there.
At line 181 of `/usr/lib/python2.7/site-packages/googlevoice/util.py`, it was:
`assert is_sha1(id), 'Message id not a SHA1 hash'`
Comment that out, and put these two lines:
```
#assert is_sha1(id), 'Message id not a SHA1 hash'
assert type(id) is StringType, "Message ID is not a string: %r" % type(id)
assert is_sha1(id), "Message ID not a SHA1 hash: %r" % id
```

**Comment by sshanmu3** [comment]
@dov1
When I  am trying to place a call without giving forwardingNumber then the call is not working and shows following error. But works fine when I have forwardingNumber used in my code.
Please provide solution to place a call without providing the forwardingNumber.

  File "C:\Python27\lib\site-packages\googlevoice\voice.py", line 158, in call
    'remember': '1'
  File "C:\Python27\lib\site-packages\googlevoice\voice.py", line 289, in __validate_special_page
    load_and_validate(self.__do_special_page(page, data))
  File "C:\Python27\lib\site-packages\googlevoice\util.py", line 70, in load_and_validate
    validate_response(loads(response.read()))
  File "C:\Python27\lib\site-packages\googlevoice\util.py", line 64, in validate_response
    raise ValidationError('There was a problem with GV: %s' % response)
googlevoice.util.ValidationError: There was a problem with GV: {u'data': {u'code': 1}, u'ok': False}

**Comment by dov1** [comment]
You can put the forwarding number in .gvoice instead of directly in the
code so that it's easily changeable.

Maybe I'm not understanding the question but if you don't provide the
number somewhere, how is Google supposed to know which number you want to
use to place the call?

**Comment by sshanmu3** [comment]
@dov1 
I have my google voice number which is linked with my mobile phone number. 
If I remove the linked mobile number from google voice account then placing the call not working.
If my google voice number have linked number then my code able to place the call without any issue.
Is google voice reacquires linked phone number to place the call? 
Suppose my google voice number is NOT Linked with any external phone number then can we not place a call via Hangouts?

**Comment by dov1** [comment]
I haven't looked into or confirmed this but I think Hangouts is using the
XMPP protocol which is how Voice places the call with Google Chat. It could
be done that way using Google APIs. But pygooglevoice​ is making use of the
click-to-call functionality to be able to place the call with linked
numbers.

**Comment by chris001** [comment]
@sshanmu3 
Did that used to work?  With a previous version, were you able to place a call with this script, and have it ring the called party, at the same time as ring your Hangouts app for you to pick up?

**Comment by dov1** [comment]
It's possible to have Google ring numbers and hangouts at the same time but I don't think pygooglevoice was able to place a call using Hangouts at any time. 

Although I don't remember the click to call function being able to use Google Chat, I see that Google did add the option to use Hangouts. Should be something interesting to look into. This might be possible.

**Comment by sshanmu3** [comment]
@chris001 
I am using latest updated file Settings.py. The master version had login issue.
The current version works fine when I have google voice number has linked number.The call comes to my phone first and ring goes to called party. I did not try calling hangout app.

**Comment by chris001** [comment]
@sshanmu3 Just so you know, the current master version was fixed 10 days ago, and it has the update (to the `settings.py`) which fixed the login issue.
And so in answer to my question, you've never used this python program to place a call between a non-forwarded google voice number (which is the same thing as the Hangouts app) and your called party.  It's good to know this.

**Comment by chris001** [comment]
@dov1 @numericOverflow @tom-slick 
I'm getting a login error today.  On 2 different gvoice accounts, using password login.
Is it crashing for you too?
```
$ gvoice send_sms +18005551212 Test Message...
Traceback (most recent call last):
  File "/usr/bin/gvoice", line 79, in <module>
    login()
  File "/usr/bin/gvoice", line 49, in login
    voice.login(options.email,options.passwd)
  File "/usr/lib/python2.7/site-packages/googlevoice/voice.py", line 75, in login
    galx = re.search(r"type=\"hidden\"\s+name=\"GALX\"\s+value=\"(.+)\"", content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by dov1** [comment]
I didn't notice any problem placing calls. I rarely use the script for sms. I can test it later or tomorrow.

**Comment by kenttse** [comment]
I am able to login (right now) and send sms, using the exact command you used @chris001.

**Comment by chris001** [comment]
@dov1 @kenttse 
The only reason I can think of to explain why your login worked with the March 2017 code, and my login crashed, is maybe because I'm in a different geographical area from you, and have received the updated ARIA AngularJS login site before you.  When you view it using the web browser, does it look like you are still on the older gvoice site (first version AngularJS)?  Which geographical area are you in?

**Comment by MrCreosote** [comment]
@chris001 FWIW I see the same error when running `gvoice login` and entering the email address + pwd at the prompts. This is with a brand new pip install of pygooglevoice 0.5.2 on Ubuntu 14.04.

**Comment by chris001** [comment]
@MrCreosote  What's the pip install command you used

**Comment by MrCreosote** [comment]
@chris001 `sudo pip install pygooglevoice`

**Comment by chris001** [comment]
@MrCreosote 
The version on pypi was uploaded to pypi on Aug 24, 2016.  It's way out of date.
You can download the one from my organization's repo it's the most up to date.
To do this, you just run these commands:
```
cd ~
git clone https://github.com/EspaceNetworks/pygooglevoice
cd pygooglevoice
pip install -r requirements.txt
python setup.py install
cp -p bin/gvoice /usr/bin/.
exit
```

**Comment by gpratt3151** [comment]
If you're getting login failures try commenting the  `smsKey=` line in your .gvoice file unless you'have a value for it:
```bash
# Optional 2-step authentication key (as provided by Google)
#smsKey=
```
It seems that once I logged in properly one time or after some timeout period, logins started working. I cannot confirm definitively that commenting the `smsKey` is the solution, though.

**Comment by chris001** [comment]
@gpratt3151 
Thanks. I've logged in OK with `smsKey=` as it is, not commented, so it's probably not that.
I think you need to do the DisplayUnlockCaptcha ("DUC") page, it's required before logging in from a  new IP address and/or new device or app.
https://accounts.google.com/DisplayUnlockCaptcha

**Comment by Abolfazl** [comment]
I kept getting an error on `assert self.special`. I took @dov1's suggestion and hardcoded the `_rnr_se` value. To find this value, you go to https://www.google.com/voice/b/0#inbox and then view the source and search for `_rnr_se`. You will see a line that looks like `<input name="_rnr_se" type="hidden" value="nYSv//pGk54MpzGyuHthW/XXX="/>`. In `voice.py`, change the sp variable in `special()` to be equal to this instead of the `pattern.search(resp).group(2)`

**Comment by chris001** [comment]
@Abolfazl 
By getting an error on `assert self.special` this means your login failed for security reasons most likely you're running this, and so it's trying to login, from a device/IP address where it hasn't previously run. Try the DUC page ( https://accounts.google.com/DisplayUnlockCaptcha ), then try the command line again, it should work, post back here your results.
