### ISSUE TITLE
Cannot validate response

### ISSUE THREAD

**Issue by HackerQuaker** [pettazz/pygooglevoice#44]
I can only call from my Google Voice. I cannot send text messages since I have not selected any phone number to use. 

My code:
```
from googlevoice import Voice
from googlevoice.util import input

voice = Voice()
voice.login()

outgoingNumber = input('Number to call: ')
forwardingNumber = input('Number to call from [optional]: ') or None

voice.call(outgoingNumber, forwardingNumber)

if input('Calling now... cancel?[y/N] ').lower() == 'y':
    voice.cancel(outgoingNumber, forwardingNumber)
```

My error:
```
Traceback (most recent call last):
  File "callMeMaybe.py", line 10, in <module>
    voice.call(outgoingNumber, forwardingNumber)
  File "C:\Python27\lib\site-packages\googlevoice\voice.py", line 155, in call
    'phoneType': phoneType
  File "C:\Python27\lib\site-packages\googlevoice\voice.py", line 287, in __validate_special_page
    load_and_validate(self.__do_special_page(page, data))
  File "C:\Python27\lib\site-packages\googlevoice\util.py", line 65, in load_and_validate
    validate_response(loads(response.read()))
  File "C:\Python27\lib\site-packages\googlevoice\util.py", line 59, in validate_response
    raise ValidationError('There was a problem with GV: %s' % response)
googlevoice.util.ValidationError: There was a problem with GV: {'data': {'code': 1}, 'ok': False}
```

Thank you.

**Comment by chris001** [comment]
You're saying you're trying to send sms from code and it doesn't work?
What code are you using?
What happens when you try this code?
```
from googlevoice import Voice
from googlevoice.util import input

voice = Voice()
voice.login()

phoneNumber = input('Number to send message to: ')
text = input('Message text: ')

voice.send_sms(phoneNumber, text)
```

**Comment by HackerQuaker** [comment]
Hello Chris,

I am not interested in sending text messages since I am in Canada and I can't register a US number. When I try to run the code up there, I get presented with the error messages I quoted in my second code block.

Thanks.

**Comment by HackerQuaker** [comment]
Hello Chris,

I can't send SMS because I am in Canada.
I am using the code from my **first code block** and when I do, I get the error in my **second code block**.
When I run your code, I put in my phone number with the +1. And I get this error:

`Traceback (most recent call last):
  File "textMeMaybe.py", line 10, in <module>
    voice.send_sms(phoneNumber, text)
  File "C:\Python27\lib\site-packages\googlevoice\voice.py", line 190, in send_sms
    self.__validate_special_page('sms', {'phoneNumber': phoneNumber, 'text': text})
  File "C:\Python27\lib\site-packages\googlevoice\voice.py", line 287, in __validate_special_page
    load_and_validate(self.__do_special_page(page, data))
  File "C:\Python27\lib\site-packages\googlevoice\util.py", line 65, in load_and_validate
    validate_response(loads(response.read()))
  File "C:\Python27\lib\site-packages\googlevoice\util.py", line 59, in validate_response
    raise ValidationError('There was a problem with GV: %s' % response)
googlevoice.util.ValidationError: There was a problem with GV: {'data': {'code': 2046}, 'ok': False}`

**Comment by chris001** [comment]
@HackerQuaker 
* Are you saying that GV will refuse to send an SMS from you because it can detect your computer's geographical location?  What's the exact error message it gives indicating this?
* Does your GV phone number have a US area code?
* Is your `number to call` US or Canadian?
* Is your `number to call from` US or Canadian?
* Is your `number to send message to` US or Canadian?

**Comment by HackerQuaker** [comment]
@chris001 

![image](https://user-images.githubusercontent.com/13822198/28128216-029ff19c-66fd-11e7-8244-050ce36903c6.png)

- I was under the impression that I can make calls without a GV number, but to send text messages, I would need a GV number. When I try to register a US GV number with my Canadian Number, I am told that GV is only open to US users. Maybe I should open a Gmail account with a US VPN server, use a US number to verify myself and then pick a US number. But then, would I have to connect through the VPN every time I use the script? 

![image](https://user-images.githubusercontent.com/13822198/28128512-eed6bc30-66fd-11e7-90b4-8a553bd82378.png)

![image](https://user-images.githubusercontent.com/13822198/28128557-1a71d956-66fe-11e7-9445-046f55fd2266.png)

- It's weird. I am able to add a number using a US phone number with my CA IP. But then the process gets halted after I verify the code they send to my US phone number. So when I go the SMS option on GV, they ask me to sign up for a US phone number . . . . .Should I select one of these numbers for the "number to call from" in the settings.py?

- Number to call is CA.
- Number to send message to is CA.

Thank you, Chris.

**Comment by chris001** [comment]
@HackerQuaker 
The way GV works is, GV will assign you a US phone number, but only if you pass the verification step, where GV sends a SMS message (or voice call with robot voice) with a verification code, to your US mobile or landline number.  So if you're in Canada, you could only sign up for GV if you have a US mobile or landline number available one time for the GV verification step.

**Comment by HackerQuaker** [comment]
@chris001 
I have an app with a US phone number. I put in the verification code, but then after I get the number, I am asked to get the GV number again. Very confusing. Do you know why I got the initial error messages?

**Comment by chris001** [comment]
@Heck
I'm relatively certain you can't use GV for calls OR texts unless you are able to successfully verify and obtain your GV phone number.  So your only choice would be to first completely register thru a US VPN.

**Comment by HackerQuaker** [comment]
Thanks for your prompt replies dude. @chris001
