### ISSUE TITLE
Running gvoice li returning urllib2.HTTPError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by bryanlavergne** [pettazz/pygooglevoice#53]
I've been experiencing the seemingly inevitable problem of trying to only login with pygooglevoice. I've gotten this far, but am now stuck with this error.

After using `pip2.7 install` (my Python 3.6 installs have returned errors with the configparser) and setting up my `.gvoice` file, I get the following after running `gvoice li` from terminal in OS X 10.13.4.

I've had a hard time parsing the code as to how the URL is built; not sure what to do. 

```Traceback (most recent call last):
  File "/usr/local/bin/gvoice", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/bryanlavergne/Programming/Python/pygooglevoice/bin/gvoice", line 79, in <module>
    login()
  File "/Users/bryanlavergne/Programming/Python/pygooglevoice/bin/gvoice", line 49, in login
    voice.login(options.email,options.passwd)
  File "/Users/bryanlavergne/Programming/Python/pygooglevoice/googlevoice/voice.py", line 76, in login
   result = self.__do_page('login_post', {'Email': email, 'Passwd': passwd, 'gxf': gxf})
  File "/Users/bryanlavergne/Programming/Python/pygooglevoice/googlevoice/voice.py", line 280, in __do_page
    return urlopen(Request(pageuri, data, headers))
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

**Comment by chris001** [comment]
Looks like the `li` (login) command is broken.  You can just run the `gvoice` command and it will either prompt you to login interactively, or log in with the credentials saved in your user's `.gvoice` settings file saved in your home directory.

**Comment by bryanlavergne** [comment]
I used `gvoice` alone without the `li` command and it returned the same error. I tried removing my username and password from `.gvoice` then using `gvoice` again, which in then prompted for my username and password. But, after all that, it returns the same error.

Seems like we're still stuck at the same issue, even after not using `li`.

**Comment by chris001** [comment]
Which version you using?  From this repo the `master` branch?

**Comment by bryanlavergne** [comment]
Correct. I made sure to delete everything and I downloaded the `master` branch from this repo (`pettazz/pygooglevoice`).

I used `pip2.7 install`

**Comment by chris001** [comment]
Did you perform the DUC  (display unlock captcha) on your G account for the purposes of allowing cleartext password login from your previously unseen (to google) IP address?  https://accounts.google.com/b/0/displayunlockcaptcha

**Comment by bryanlavergne** [comment]
I did try that, I saw that in another Issues thread. 

I tried it again just now and confirmed that I did not have Multi-factor Authentication on as well. Used `gvoice`, typed in my info, same HTTP Error 400 return.

**Comment by chris001** [comment]
Can you try opening a browser from the same OS X machine and log into voice.google.com web interface

**Comment by bryanlavergne** [comment]
Tried it now, I was able to log in.

I was already logged in in my current browser session; so I logged out, went to `voice.google.com`, clicked Sign In, had to select the name of my account since it recognizes my browser, it prompted for a password then succeeded.

**Comment by chris001** [comment]
OK great so the command `gvoice` is logging in now for you.  These login issues come down to tighter login restrictions on the G side on letting unseen devices log in with valid credentials, due to higher rates of stolen credentials being used to attempt to login to G accounts from new IP addresses or from new devices.

**Comment by bryanlavergne** [comment]
I should clarify, sorry: I was able to log into the web interface.

’gvoice’ still returns the same error as above.

**Comment by chris001** [comment]
Can you try it again with the code from this repo: https://github.com/EspaceNetworks/pygooglevoice
